classdef FigureHelper
    methods (Static)

        % ============================================================
        % 전체 시스템 배치 출력
        % ============================================================
        function plotSystemDeployment( ...
                SatelliteNode, ...
                Beams, ...
                UTs, ...
                APJNode, ...
                maxBeamFootprintDiameter)

            %% =====================================================
            % Figure 생성
            % ======================================================
            figure( ...
                'Name', 'System Deployment', ...
                'NumberTitle', 'off', ...
                'Units', 'normalized', ...
                'Position', [0.03 0.05 0.88 0.88] ...
            );

            hold on;
            grid on;
            axis equal;
            box on;

            ax = gca;

            ax.FontSize = 12;
            ax.LineWidth = 1;
            ax.TickDir = 'out';

            % Grid를 너무 진하지 않게
            ax.GridAlpha = 0.15;
            ax.MinorGridAlpha = 0.10;

            theta = linspace(0, 2*pi, 500);


            %% =====================================================
            % Satellite Beam Footprint
            % ======================================================
            footprintRadius_km = ...
                (maxBeamFootprintDiameter / 2) / 1e3;

            footprintX = ...
                footprintRadius_km * cos(theta);

            footprintY = ...
                footprintRadius_km * sin(theta);

            hFootprint = plot( ...
                footprintX, ...
                footprintY, ...
                'k--', ...
                'LineWidth', 2 ...
            );


            %% =====================================================
            % Beam 영역
            % ======================================================
            hBeam = [];
            hBeamCenter = [];

            for beamIndex = 1:numel(Beams)

                beam = Beams(beamIndex);

                centerX_km = ...
                    beam.CenterPosition(1) / 1e3;

                centerY_km = ...
                    beam.CenterPosition(2) / 1e3;

                radius_km = ...
                    beam.Radius / 1e3;


                % Beam 원
                beamX = ...
                    centerX_km ...
                    + radius_km * cos(theta);

                beamY = ...
                    centerY_km ...
                    + radius_km * sin(theta);


                % Beam 경계
                currentBeam = plot( ...
                    beamX, ...
                    beamY, ...
                    'b-', ...
                    'LineWidth', 1.0 ...
                );


                % Beam 중심
                currentCenter = plot( ...
                    centerX_km, ...
                    centerY_km, ...
                    'bx', ...
                    'MarkerSize', 8, ...
                    'LineWidth', 1.5 ...
                );


                % Legend는 첫 번째 Beam만 사용
                if beamIndex == 1
                    hBeam = currentBeam;
                    hBeamCenter = currentCenter;
                end

            end


            %% =====================================================
            % UT 위치
            % ======================================================
            hUT = [];
            hTargetUT = [];

            for utIndex = 1:numel(UTs)

                ut = UTs(utIndex);

                utX_km = ...
                    ut.Position(1) / 1e3;

                utY_km = ...
                    ut.Position(2) / 1e3;


                % Target UT
                if ut.IsTarget

                    hTargetUT = plot( ...
                        utX_km, ...
                        utY_km, ...
                        'r*', ...
                        'MarkerSize', 13, ...
                        'LineWidth', 2 ...
                    );

                % Normal UT
                else

                    currentUT = plot( ...
                        utX_km, ...
                        utY_km, ...
                        'ko', ...
                        'MarkerSize', 6, ...
                        'MarkerFaceColor', 'w', ...
                        'LineWidth', 1.2 ...
                    );

                    % Legend는 첫 번째 Normal UT만 사용
                    if isempty(hUT)
                        hUT = currentUT;
                    end

                end

            end


            %% =====================================================
            % APJ 위치
            % ======================================================
            hAPJ = [];

            if ~isempty(APJNode)

                apjX_km = ...
                    APJNode.Position(1) / 1e3;

                apjY_km = ...
                    APJNode.Position(2) / 1e3;


                hAPJ = plot( ...
                    apjX_km, ...
                    apjY_km, ...
                    'md', ...
                    'MarkerSize', 10, ...
                    'MarkerFaceColor', 'm', ...
                    'LineWidth', 1.5 ...
                );


                %% -------------------------------------------------
                % Target UT ↔ APJ 연결선
                % --------------------------------------------------
                targetUT = ...
                    UTs(APJNode.TargetUTId);

                targetX_km = ...
                    targetUT.Position(1) / 1e3;

                targetY_km = ...
                    targetUT.Position(2) / 1e3;


                plot( ...
                    [targetX_km apjX_km], ...
                    [targetY_km apjY_km], ...
                    'm--', ...
                    'LineWidth', 1.2, ...
                    'HandleVisibility', 'off' ...
                );

            end


            %% =====================================================
            % Satellite Ground Projection
            % ======================================================
            satelliteX_km = ...
                SatelliteNode.Position(1) / 1e3;

            satelliteY_km = ...
                SatelliteNode.Position(2) / 1e3;


            hSatellite = plot( ...
                satelliteX_km, ...
                satelliteY_km, ...
                'ks', ...
                'MarkerSize', 11, ...
                'MarkerFaceColor', 'k', ...
                'LineWidth', 1.2 ...
            );


            %% =====================================================
            % Axis 설정
            % ======================================================
            margin_km = 30;

            xlim([ ...
                -footprintRadius_km - margin_km, ...
                 footprintRadius_km + margin_km ...
            ]);

            ylim([ ...
                -footprintRadius_km - margin_km, ...
                 footprintRadius_km + margin_km ...
            ]);


            xlabel( ...
                'X Position [km]', ...
                'FontSize', 13 ...
            );

            ylabel( ...
                'Y Position [km]', ...
                'FontSize', 13 ...
            );


            title( ...
                'Satellite Beam and Ground Node Deployment', ...
                'FontSize', 15, ...
                'FontWeight', 'bold' ...
            );


            %% =====================================================
            % Legend 생성
            % ======================================================
            legendHandles = [];
            legendLabels = {};


            % Beam Footprint
            legendHandles(end+1) = ...
                hFootprint;

            legendLabels{end+1} = ...
                'Beam footprint boundary';


            % Beam
            if ~isempty(hBeam)

                legendHandles(end+1) = ...
                    hBeam;

                legendLabels{end+1} = ...
                    'Beam';

            end


            % Beam Center
            if ~isempty(hBeamCenter)

                legendHandles(end+1) = ...
                    hBeamCenter;

                legendLabels{end+1} = ...
                    'Beam center';

            end


            % Normal UT
            if ~isempty(hUT)

                legendHandles(end+1) = ...
                    hUT;

                legendLabels{end+1} = ...
                    'UT';

            end


            % Target UT
            if ~isempty(hTargetUT)

                legendHandles(end+1) = ...
                    hTargetUT;

                legendLabels{end+1} = ...
                    'Target UT';

            end


            % APJ
            if ~isempty(hAPJ)

                legendHandles(end+1) = ...
                    hAPJ;

                legendLabels{end+1} = ...
                    'APJ';

            end


            % Satellite
            legendHandles(end+1) = ...
                hSatellite;

            legendLabels{end+1} = ...
                'Satellite ground projection';


            legend( ...
                legendHandles, ...
                legendLabels, ...
                'Location', 'eastoutside', ...
                'FontSize', 10 ...
            );


            hold off;

        end

    end
end